name: Update Resume Gist

on: push

jobs:
  update-resume-gist:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Convect resume yaml to json
      uses: fabasoad/data-format-converter-action@v0
      id: yaml2json
      with:
        input: "resume.yaml"
        from: "yaml"
        to: "json"
    - name: Print result
      run: echo "${{ steps.yaml2json.outputs.output }}"
  
    - name: Update Resume Gist
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.TOKEN }}
        gist_id: c9dcfa1b37dec07fb2ee7f36d7278105
        file_path: resume.json
