name: Transfor resume.yaml to gist
on: 
 push:
 workflow_dispatch:
 
jobs:
  update-resume-gist:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Convect resume yaml to json
      uses: fabasoad/data-format-converter-action@v0
      id: yaml2json
      with:
        input: "resume.yaml"
        from: "yaml"
        to: "json"
    - name: Print result with cat
      run: |
        cat << EOF > resume.json
        ${{ steps.yaml2json.outputs.output }}
        EOF
    - name: Update Resume Gist
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.TOKEN }}
        gist_id: ab0802ef51ac9f53defe686e7fae452b
        file_path: resume.json
