name: Update Resume Gist

on: push

jobs:
  update-resume-gist:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Transform resume in yaml format to json
      uses: fabasoad/yaml-json-xml-converter-action@main
        id: json2yaml
        with:
          path: 'resume.yml'
          from: 'yaml'
          to: 'json'
    - name: Update Resume Gist
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.TOKEN }}
        gist_id: c9dcfa1b37dec07fb2ee7f36d7278105
        file_path: resume.json
